/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: EditorialImage;
  body?: Body;
  seo?: Seo;
  projectType?: "Client work" | "Self-initiated concept";
  disciplines?: Array<string>;
  gallery?: Array<
    {
      _key: string;
    } & EditorialImage
  >;
  videoUrl?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: EditorialImage;
  body?: Body;
  seo?: Seo;
  author?: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: EditorialImage;
};

export type Body = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & EditorialImage)
>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type EditorialImage = {
  _type: "editorialImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  credit?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  bio?: string;
  portrait?: EditorialImage;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | CaseStudy
  | AuthorReference
  | CategoryReference
  | Post
  | Seo
  | Body
  | SanityImageAssetReference
  | EditorialImage
  | Slug
  | Category
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../cult/lib/sanity/client.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc){_id, title, "slug": slug.current, excerpt, publishedAt, coverImage, author->{name}, categories[]->{title}}
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  coverImage: EditorialImage | null;
  author: {
    name: string | null;
  } | null;
  categories: Array<{
    title: string | null;
  }> | null;
}>;

// Source: ../cult/lib/sanity/client.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{_id, title, excerpt, publishedAt, coverImage, body, seo, author->{name,bio}, categories[]->{title}}
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  coverImage: EditorialImage | null;
  body: Body | null;
  seo: Seo | null;
  author: {
    name: string | null;
    bio: string | null;
  } | null;
  categories: Array<{
    title: string | null;
  }> | null;
} | null;

// Source: ../cult/lib/sanity/client.ts
// Variable: CASE_STUDIES_QUERY
// Query: *[_type == "caseStudy" && defined(slug.current)] | order(_createdAt desc){_id, title, "slug": slug.current, excerpt, coverImage, projectType, disciplines, body, gallery, videoUrl, seo}
export type CASE_STUDIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  coverImage: EditorialImage | null;
  projectType: "Client work" | "Self-initiated concept" | null;
  disciplines: Array<string> | null;
  body: Body | null;
  gallery: Array<
    {
      _key: string;
    } & EditorialImage
  > | null;
  videoUrl: string | null;
  seo: Seo | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "post" && defined(slug.current)] | order(publishedAt desc){_id, title, "slug": slug.current, excerpt, publishedAt, coverImage, author->{name}, categories[]->{title}}': POSTS_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0]{_id, title, excerpt, publishedAt, coverImage, body, seo, author->{name,bio}, categories[]->{title}}': POST_QUERY_RESULT;
    '*[_type == "caseStudy" && defined(slug.current)] | order(_createdAt desc){_id, title, "slug": slug.current, excerpt, coverImage, projectType, disciplines, body, gallery, videoUrl, seo}': CASE_STUDIES_QUERY_RESULT;
  }
}
