import {chromium} from 'playwright';import AxeBuilder from '@axe-core/playwright';import assert from 'node:assert/strict';import fs from 'node:fs';
const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const report=[],failures=[],errors=[],mutations=[];
for(const width of [1440,390,360]){const c=await b.newContext({viewport:{width,height:1000}});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.method()!=='GET')mutations.push(r.url())});await p.addInitScript(()=>{window.shifts=[];new PerformanceObserver(l=>l.getEntries().forEach(e=>{if(!e.hadRecentInput)window.shifts.push(e.value)})).observe({type:'layout-shift',buffered:true});});await p.goto('http://127.0.0.1:4179/work/hardline/');await p.evaluate(()=>document.fonts.ready);
 const routing=p.locator('.hl-routing');await routing.scrollIntoViewIfNeeded();await routing.getByRole('button',{name:/Continue/}).click();assert.equal(await p.locator('#hl-origin').evaluate(e=>e===document.activeElement),true);
 await p.getByLabel('Origin',{exact:true}).fill('   ');await p.getByLabel('Destination',{exact:true}).fill('Receiving facility');await routing.getByRole('button',{name:/Continue/}).click();assert.equal(await p.locator('#hl-origin').evaluate(e=>e.validity.valid),false);
 await routing.getByRole('button',{name:'Use an illustrative example'}).click();await routing.getByRole('button',{name:/Continue/}).click();await p.getByLabel('Ready date',{exact:true}).waitFor({timeout:5000});assert.equal(await p.locator('.hl-route-panel h3').evaluate(e=>e===document.activeElement),true);await p.getByLabel('Load requirement',{exact:true}).fill('Illustrative component — handling review required');
 console.log('Before step2',await routing.locator('input').evaluateAll(es=>es.map(e=>({id:e.id,v:e.value,valid:e.validity.valid,msg:e.validationMessage}))));await routing.getByRole('button',{name:/Continue/}).click();console.log('After step2',await routing.innerText());await p.getByLabel('Operational consequence',{exact:true}).fill('Illustrative receiving-line interruption.');await routing.getByRole('button',{name:/Routing review/}).click();await p.getByRole('status').waitFor();assert.match(await p.getByRole('status').innerText(),/Nothing has been submitted/);assert.match(await p.locator('.hl-review-manifest').innerText(),/handling review required/);
 const axe=(await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}));assert.deepEqual(axe,[]);await routing.screenshot({path:`../hardline-routing-review-${width}.png`});
 await routing.getByRole('button',{name:/Edit route/}).click();assert.equal(await p.getByLabel('Origin',{exact:true}).inputValue(),'Origin facility');await routing.getByRole('button',{name:/Continue/}).click();await routing.getByRole('button',{name:/Back/}).click();assert.equal(await p.getByLabel('Destination',{exact:true}).inputValue(),'Receiving facility');await routing.getByRole('button',{name:/Continue/}).click();await routing.getByRole('button',{name:/Continue/}).click();await routing.getByRole('button',{name:/Routing review/}).click();await routing.getByRole('button',{name:/Reset prototype/}).click();assert.equal(await p.getByLabel('Origin',{exact:true}).inputValue(),'');
 assert.equal(await p.evaluate(()=>localStorage.length+sessionStorage.length),0);
 for(const details of await p.locator('.hl-measure-register details').all()){await details.locator('summary').click();assert.ok(await details.locator('p').isVisible());}
 await p.emulateMedia({reducedMotion:'reduce'});for(const section of await p.locator('.hardline-page>section').all()){await section.scrollIntoViewIfNeeded();}assert.equal(await p.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0);
 await p.locator('.next-study-link').click();await p.waitForURL('**/work/noct/');assert.equal(await p.locator('h1').innerText(),'NOCT.');assert.equal(await p.locator('.hardline-page').count(),0);report.push({width,validation:true,review:true,edit:true,back:true,reset:true,reducedMotion:true,nextStudy:true});await c.close();}
assert.deepEqual(errors,[]);assert.deepEqual(mutations,[]);fs.writeFileSync('../hardline-interactions.json',JSON.stringify({report,errors,mutations,failures},null,2));console.log('Routing prototype, accessible focus/validation, edit/back/reset, zero storage/submission, reduced motion and NOCT transition pass at 1440/390/360.');await b.close();
