import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const context=await browser.newContext({viewport:{width:1440,height:900}});
const page=await context.newPage();const errors=[];const requests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>{if(!r.url().endsWith('.mp4')&&!r.failure()?.errorText.includes('ERR_ABORTED'))errors.push(r.url()+':'+r.failure()?.errorText)});
page.on('request',r=>{if(r.url().endsWith('.mp4'))requests.push(r.url())});
await page.goto('http://127.0.0.1:4179/');
await page.waitForTimeout(1500);
console.log('media',await page.locator('video').evaluateAll(els=>els.map(v=>({src:v.src,state:v.readyState,paused:v.paused,time:v.currentTime,error:v.error?.message}))));
await page.waitForFunction(()=>document.querySelector('.is-displayed video')?.currentTime>.1);
assert.equal(await page.locator('video').count(),3);
assert.equal(await page.locator('video').evaluateAll(vs=>vs.filter(v=>!v.paused).length),1);
const box=await page.locator('.hero').boundingBox();
await page.getByRole('tab',{name:'03 Media',exact:true}).click();
assert.equal(await page.getByRole('tab',{name:'03 Media',exact:true}).getAttribute('aria-selected'),'true');
await page.waitForTimeout(150);
const blend=await page.locator('.hero-film-layer').evaluateAll(es=>es.map(e=>({class:e.className,opacity:+getComputedStyle(e).opacity})));
console.log('blend',blend);assert.ok(blend.some(e=>e.class.includes('is-outgoing')&&e.opacity===1));assert.ok(blend.some(e=>e.class.includes('is-displayed')&&e.opacity>0&&e.opacity<1));
await page.waitForTimeout(1000);assert.equal(await page.locator('.hero').boundingBox().then(b=>b.height),box.height); assert.equal(await page.locator('.hero').boundingBox().then(b=>b.width),box.width);
for(const name of ['04 Search','05 Conversion','06 Measurement','01 Strategy','02 Creative']) await page.getByRole('tab',{name,exact:true}).click();
await page.waitForTimeout(1100);assert.equal(await page.locator('.is-displayed').count(),1);assert.equal(await page.locator('video').count(),3);
await page.getByRole('button',{name:'Pause all films',exact:true}).first().click();assert.equal(await page.locator('video').count(),0);
await page.locator('.thesis h2').evaluate(el=>{document.documentElement.style.scrollBehavior='auto';scrollTo(0,el.getBoundingClientRect().top+scrollY-innerHeight*.5)});
await page.waitForTimeout(130);
console.log('thesis',await page.locator('.thesis').evaluate(el=>el.getAnimations({subtree:true}).map(a=>({target:a.effect.target.tagName,text:a.effect.target.textContent,duration:a.effect.getTiming().duration,delay:a.effect.getTiming().delay}))));
assert.ok(await page.locator('.thesis').evaluate(el=>el.getAnimations({subtree:true}).length)>=4);
await page.waitForTimeout(1200);assert.equal(await page.locator('.thesis').evaluate(el=>el.getAnimations({subtree:true}).length),0);
await page.emulateMedia({reducedMotion:'reduce'});
await page.goto('http://127.0.0.1:4179/');await page.waitForTimeout(500);assert.equal(await page.locator('video').count(),0);
await page.locator('.thesis').scrollIntoViewIfNeeded();assert.equal(await page.locator('.thesis').evaluate(el=>el.getAnimations({subtree:true}).length),0);
for(const width of [1440,1280,1024,768,390,360]) { await page.setViewportSize({width,height:844});for(const route of ['/','/services/','/work/','/about/','/contact/']) {await page.goto('http://127.0.0.1:4179'+route);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${width}${route}`);assert.equal(await page.locator('h1').count(),1);} }
await page.emulateMedia({reducedMotion:'no-preference'});await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:4179/');await page.waitForTimeout(300);assert.equal(await page.locator('video').count(),0);
await page.getByRole('button',{name:'Menu',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Close',exact:true}).getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'Menu',exact:true}).evaluate(e=>e===document.activeElement),true);
await page.getByRole('tab',{name:/Measurement/}).click();await page.waitForTimeout(1000);
await page.getByRole('button',{name:'Play films',exact:true}).first().click();await page.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';scrollTo(0,0)});await page.waitForFunction(()=>document.querySelector('.is-displayed video')?.currentTime>.1);assert.ok(await page.locator('video').evaluateAll(es=>es.every(e=>e.src.includes('-mobile.mp4'))));
await page.screenshot({path:'../motion-mobile.png'});await page.setViewportSize({width:1440,height:900});await page.goto('http://127.0.0.1:4179/');await page.waitForTimeout(1100);await page.screenshot({path:'../motion-desktop.png'});
await fs.writeFile('../motion-qa.json',JSON.stringify({errors,requests:[...new Set(requests)],blend},null,2));assert.deepEqual(errors,[]);console.log('PASS: layers, buffer, active playback, rapid switches, no hero layout shift, thesis sequence, reduced motion, 30 route/width checks, mobile playback/menu, no page errors.');await browser.close();
